version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore MarketDataContributionAPI/MarketDataContributionAPI.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build MarketDataContributionAPI/MarketDataContributionAPI.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o ./ MarketDataContributionAPI/MarketDataContributionAPI.csproj

artifacts:
  files:
    - '**/*'