version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:  
      - /usr/local/bin/dotnet-install.sh --channel LTS

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore MarketDataContributionAPI.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build MarketDataContributionAPI.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release ./build_output MarketDataContributionAPI.csproj

artifacts:
  files:
    - '**/*'